"""mechanic permission

Revision ID: 62218f935509
Revises: 544936363a26
Create Date: 2026-02-11 20:07:23.143474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62218f935509'
down_revision: Union[str, Sequence[str], None] = '544936363a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanic_permission_id'), 'mechanic_permission', ['id'], unique=False)
    op.create_index(op.f('ix_mechanic_permission_key'), 'mechanic_permission', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanic_permission_key'), table_name='mechanic_permission')
    op.drop_index(op.f('ix_mechanic_permission_id'), table_name='mechanic_permission')
    op.drop_table('mechanic_permission')
    # ### end Alembic commands ###
