"""mechanic comment

Revision ID: 652db811c8ef
Revises: 97b6b66ef34e
Create Date: 2026-02-13 01:08:38.828680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652db811c8ef'
down_revision: Union[str, Sequence[str], None] = '97b6b66ef34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['mechanic_comment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanic_comment_id'), 'mechanic_comment', ['id'], unique=False)
    op.create_index(op.f('ix_mechanic_comment_mechanic_id'), 'mechanic_comment', ['mechanic_id'], unique=False)
    op.create_index(op.f('ix_mechanic_comment_parent_id'), 'mechanic_comment', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanic_comment_parent_id'), table_name='mechanic_comment')
    op.drop_index(op.f('ix_mechanic_comment_mechanic_id'), table_name='mechanic_comment')
    op.drop_index(op.f('ix_mechanic_comment_id'), table_name='mechanic_comment')
    op.drop_table('mechanic_comment')
    # ### end Alembic commands ###
