"""car and mechanic car request

Revision ID: 97b6b66ef34e
Revises: 84c6d4e827ea
Create Date: 2026-02-12 17:36:31.252553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b6b66ef34e'
down_revision: Union[str, Sequence[str], None] = '84c6d4e827ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('car_type', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tip', sa.String(length=100), nullable=False),
    sa.Column('model', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('license_plate', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    op.create_index(op.f('ix_car_user_id'), 'car', ['user_id'], unique=False)
    op.create_table('mechanic_car_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'under_repair', 'repaired', 'delivered', name='mechanic_car_request_status'), nullable=False),
    sa.Column('issue', sa.Enum('motor', 'gear_box', 'electronic', 'suspension_system', 'other', name='mechanic_car_request_issue'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanic_car_request_car_id'), 'mechanic_car_request', ['car_id'], unique=False)
    op.create_index(op.f('ix_mechanic_car_request_id'), 'mechanic_car_request', ['id'], unique=False)
    op.create_index(op.f('ix_mechanic_car_request_mechanic_id'), 'mechanic_car_request', ['mechanic_id'], unique=False)
    op.add_column('mechanic', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mechanic', 'created_at')
    op.drop_index(op.f('ix_mechanic_car_request_mechanic_id'), table_name='mechanic_car_request')
    op.drop_index(op.f('ix_mechanic_car_request_id'), table_name='mechanic_car_request')
    op.drop_index(op.f('ix_mechanic_car_request_car_id'), table_name='mechanic_car_request')
    op.drop_table('mechanic_car_request')
    op.drop_index(op.f('ix_car_user_id'), table_name='car')
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
