"""mechanic comments

Revision ID: b6fd7f849c42
Revises: e77fe5223a7d
Create Date: 2026-02-13 10:42:51.515649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fd7f849c42'
down_revision: Union[str, Sequence[str], None] = 'e77fe5223a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_comment', sa.Column('mechanic_request_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_mechanic_comment_mechanic_id'), table_name='mechanic_comment')
    op.create_index(op.f('ix_mechanic_comment_mechanic_request_id'), 'mechanic_comment', ['mechanic_request_id'], unique=False)
    op.drop_constraint(op.f('mechanic_comment_mechanic_id_fkey'), 'mechanic_comment', type_='foreignkey')
    op.create_foreign_key(None, 'mechanic_comment', 'mechanic_car_request', ['mechanic_request_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mechanic_comment', 'mechanic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_comment', sa.Column('mechanic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mechanic_comment', type_='foreignkey')
    op.create_foreign_key(op.f('mechanic_comment_mechanic_id_fkey'), 'mechanic_comment', 'mechanic', ['mechanic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_mechanic_comment_mechanic_request_id'), table_name='mechanic_comment')
    op.create_index(op.f('ix_mechanic_comment_mechanic_id'), 'mechanic_comment', ['mechanic_id'], unique=False)
    op.drop_column('mechanic_comment', 'mechanic_request_id')
    # ### end Alembic commands ###
