"""user mechanic commnet

Revision ID: e77fe5223a7d
Revises: 652db811c8ef
Create Date: 2026-02-13 01:22:07.170572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77fe5223a7d'
down_revision: Union[str, Sequence[str], None] = '652db811c8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_comment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_mechanic_comment_user_id'), 'mechanic_comment', ['user_id'], unique=False)
    op.create_foreign_key(None, 'mechanic_comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mechanic_comment', type_='foreignkey')
    op.drop_index(op.f('ix_mechanic_comment_user_id'), table_name='mechanic_comment')
    op.drop_column('mechanic_comment', 'user_id')
    # ### end Alembic commands ###
